[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:mosquitto]
command=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
user=mosquitto
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:hame-relay]
command=node dist/main.js
directory=/opt/hame-relay
priority=20
autostart=true
autorestart=true
startsecs=5
environment=NODE_ENV="production",CONFIG_PATH="/opt/hame-relay/config/config.json",CERT_PATH="/opt/hame-relay/certs"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:hm2mqtt]
command=node dist/index.js
directory=/opt/hm2mqtt
priority=20
autostart=true
autorestart=true
startsecs=5
environment=NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:forwarder]
command=node src/index.js
directory=/opt/forwarder
priority=30
autostart=true
autorestart=true
startsecs=5
environment=NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
